[project]
name = 'Decentralized-Healthcare-Provider-Credentialing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.facility-privileging]
path = 'contracts/facility-privileging.clar'
clarity_version = 2
epoch = 2.5

[contracts.license-status]
path = 'contracts/license-status.clar'
clarity_version = 2
epoch = 2.5

[contracts.provider-identity]
path = 'contracts/provider-identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.qualification-verification]
path = 'contracts/qualification-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
